- name: Enable MariaDB
  service: 
    name: mariadb
    state: started
    enabled: yes

- name: Disable Asterisk
  service:
    name: asterisk
    enabled: no
    state: stopped

- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Start FreePBX
  service:
    name: freepbx
    state: started
    enabled: yes
